export {ReactComponent as bell} from './bell.svg'
export {ReactComponent as placeholder} from './placeholder.svg'
export {ReactComponent as search} from './search.svg'
export {ReactComponent as user} from './user.svg'
export {ReactComponent as chat} from './chat.svg'
export {ReactComponent as github} from './github.svg'